# Dockerfile
# Pull the base image
FROM node:16-alpine
# Set the working directory
WORKDIR /app
# Copy app dependencies to container
# COPY ./package*.json ./
# COPY ./yarn.lock ./
COPY . /app
# Add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
# Install dependencies
# RUN yarn install
# Deploy app for local development
CMD yarn start --host 0.0.0.0 --port 3000 --disableHostCheck true